In [3]:
import numpy as np
a=np.arange(1,10,3)
print(a)

[1 4 7]


In [5]:
import numpy as np
b=np.linspace(0,1,6)
print(b)

[0.  0.2 0.4 0.6 0.8 1. ]


In [6]:
import numpy as np
c=np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np
d=np.ones((3,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
import numpy as np
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
import numpy as np
d=np.eye(3,2)
print(d)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [18]:
import numpy as np
a=np.arange(10)
print(a[2:10:2])

[2 4 6 8]


In [1]:
import numpy as np

# Define a structured data type
dtype = np.dtype([('name', 'U10'), ('age', int), ('height', float)])

# Create an array with the structured data type
data = np.array([('Alice', 25, 5.6), ('Bob', 30, 6.0)], dtype=dtype)

# Accessing fields in the structured array
print(data['name'])    # Access the 'name' field
print(data['age'])     # Access the 'age' field
print(data['height'])  # Access the 'height' field


['Alice' 'Bob']
[25 30]
[5.6 6. ]


In [12]:
import numpy as np

arr = np.array([[1, 2, 3,5], [4, 5, 6,8]])
print(arr.shape)  # This will print (2, 3) indicating a 2x3 matrix.

new_arr = arr.reshape(4, 2)  # Reshaping the 2x3 array into a 3x2 array
print(new_arr.shape)  # This will print (3, 2).



(2, 4)
(4, 2)


# reashape

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
