# Creating Arrays

In [35]:
import numpy as np
a = np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


## Arrays are faster than lists.

# 0-D Array/Scalars

In [33]:
import numpy as np
z = np.array(16)
print(z)

16


In [6]:
L=range(1000)
%timeit [i**2 for i in L]

206 µs ± 2.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# 1D-array/Vectors/Unidimensional array

In [17]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [16]:
a.ndim # print dimentions

1

In [15]:
a.shape # print shape

(4,)

In [18]:
len(a)

4

# 2-D array/Matrix

In [40]:
b = np.array([[0,1,2],[3,4,6]])
b

array([[0, 1, 2],
       [3, 4, 6]])

In [43]:
b.ndim

2

In [42]:
b.shape

(2, 3)

In [41]:
len(b)

2

# 3-D array/Tensor

In [28]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c           

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
z=np.array([1,2,3])
print(z)
print(z[:,np.newaxis])

[1 2 3]
[[1]
 [2]
 [3]]


In [13]:
a=np.arange(4*3*2).reshape(4*3*2)
print(a)
b=a.shape
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [29]:
c.ndim

3

In [30]:
c.shape

(2, 2, 2)

In [31]:
len(c)

2

# Reshape

In [2]:
import numpy as np

# Create a 5-D array with random values
array_5d = np.random.random((2, 3, 4, 5, 6))

print(array_5d)


[[[[[9.02407883e-01 3.65320267e-01 9.66611583e-01 1.88382437e-01
     9.19856404e-01 6.51516019e-02]
    [2.84353678e-01 6.56296225e-01 8.85899024e-01 9.48796783e-02
     5.07318206e-01 7.57306249e-01]
    [1.11720083e-01 6.86583086e-01 1.34129221e-01 2.15006922e-01
     1.94784882e-01 1.45130444e-01]
    [7.78665979e-01 5.97596453e-01 1.84794402e-01 4.62977669e-01
     2.66278092e-01 2.63037453e-01]
    [8.92516546e-01 6.37300452e-01 8.93690751e-02 9.19815871e-01
     7.64716454e-02 5.75507715e-02]]

   [[3.47371757e-01 4.51717291e-01 2.65107609e-01 3.26176697e-01
     3.73937123e-02 7.91059219e-01]
    [9.52836866e-01 6.73438426e-01 7.47024712e-01 3.90618603e-01
     4.74289203e-01 1.64793789e-01]
    [3.09352754e-01 6.39935693e-01 3.07045163e-01 2.48954348e-01
     5.10195722e-01 7.57479806e-01]
    [6.33738454e-01 3.41829219e-01 3.72826250e-01 5.09749995e-01
     6.35771565e-01 6.29921846e-01]
    [3.33339286e-01 6.84305570e-01 3.13585492e-01 8.11154212e-01
     5.37547776e-01 9.57

In [5]:
import numpy as np
# Create a simple 5-D array
array_5d = np.arange(120)
print(array_5d)
b = array_5d.reshape(5, 2, 3, 4, 2)
print(b)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


ValueError: cannot reshape array of size 120 into shape (5,2,3,4,2)

# Flattening

In [4]:
import numpy as np
n = np.array([[[1,2,3],[4,5,6]]])
n.ravel()

array([1, 2, 3, 4, 5, 6])

In [5]:
n.T

array([[[1],
        [4]],

       [[2],
        [5]],

       [[3],
        [6]]])

# Reshaping

In [7]:
n.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [8]:
b=n.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [9]:
c=b.reshape((2,3))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [35]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [37]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [44]:
np.diag(a)

array([1, 2, 3, 4])

In [46]:
a=np.random.rand(4)
a

array([0.1631642 , 0.49830451, 0.89859239, 0.91492236])

In [47]:
a=np.random.randn(4)
a

array([ 0.5457688 , -0.20820683,  1.15911777, -0.37863279])

In [48]:
a=np.arange(10)
a.dtype

dtype('int32')

In [50]:
a=np.arange(10,dtype='float32')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [51]:
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [52]:
d=np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [54]:
b=np.array([True,False,False,True])
#b.dtype
print(b.dtype)

bool


In [55]:
s=np.array(['Ram','Robert','Rahim'])
s.dtype

dtype('<U6')

# Indexing

In [44]:
#indexing
a=np.arange(10)
for i in a:
    print(i)
print(a[5])

0
1
2
3
4
5
6
7
8
9
5


In [60]:
a=np.diag([1,2,3])
a
#print(a[2,2])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [61]:
a[2,1]=5 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

# $\color{green}{\text{Slicing}}$ 

In [26]:
#slicing
a=np.arange(10)
print(a)
print("Slicing from backward direction -->",a[-5:-9:-1])
print(a[-4:-2])

[0 1 2 3 4 5 6 7 8 9]
Slicing from backward direction --> [5 4 3 2]
[6 7]


In [64]:
a[1:8:2]

array([1, 3, 5, 7])

In [65]:
#assignment & slicing
a=np.arange(10)
a[5:]=10 #change values to 10 from 5th element to last
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [66]:
#assigning
b=np.arange(5)
a[5:]=b[::-1]
print(a)


array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [84]:
p1= np.array([5,9,3,4,6,1])
print(p1.shape)
print(p1.ndim)

print(p1[1:4])

print(p1[0])

s=p1.reshape(2,3)
print(s)

f=s.ravel()
print(f)

p4= np.arange(2,11)
print(p4)
print("shape",p4.shape)
re=p4.reshape(1,3,3)
print(re)

ek = np.arange(2,11).reshape(1,3,3)
print(ek)


(6,)
1
[9 3 4]
5
[[5 9 3]
 [4 6 1]]
[5 9 3 4 6 1]
[ 2  3  4  5  6  7  8  9 10]
shape (9,)
[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]]
[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]]


In [88]:
r1=np.arange(5)
res=r1.resize((11,))
print(res)

None


# Arithmetic Operations

In [93]:
x=np.array([4,5,6,7])
y=np.array([4,5,6,7])
print("Add:",x+y)
print("Subtract:",x-y)
print("Divide:",x/y)
print("Multiply:",x*y)
print("Exponent:",x**y)
print(np.sqrt(x))

Add: [ 8 10 12 14]
Subtract: [0 0 0 0]
Divide: [1. 1. 1. 1.]
Multiply: [16 25 36 49]
Exponent: [   256   3125  46656 823543]
[2.         2.23606798 2.44948974 2.64575131]


In [115]:
r2 = np.array([[2,3],[4,5]])
print(r2)
r3 = np.array([[6,7],[8,9]])
print(r3)
print("-----------------")
print("Multiply:",r2*r3)
print("-----------------")
print(r2.dot(r3))
print(np.dot(r2,r3))
print("-----------------")
# print(r2.sum(r3))
# print(np.sum(r2,r3))

r4 = np.array([[6,7],[8,9]])
print(np.sum(r4, axis=0)) #column-wise
print(np.sum(r4, axis=1)) #row-wise

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]
-----------------
Multiply: [[12 21]
 [32 45]]
-----------------
[[36 41]
 [64 73]]
[[36 41]
 [64 73]]
-----------------
[14 16]
[13 17]


# Copy & Views

In [68]:
#copy & views
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [70]:
np.shares_memory(a,b)

True

In [71]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [72]:
a=np.arange(10)
c=a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [73]:
np.shares_memory(a,c)

False

In [75]:
c[0]=10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Mask
## Fancy Indexing

In [59]:
m=np.random.randint(0,20,15)
print(m)
mask = m%2==0
extract=m[mask]
print(extract)

#print(m[mask]=-7)



[17 11  9 11  8  8 11  3  4  2 19 14 17 13  5]
[ 8  8  4  2 14]


TypeError: 'extract' is an invalid keyword argument for print()

# Iterating arrays

In [61]:
import numpy as np
i = np.array([[11,12,13,14],
              [15,16,17,18]])
for x in np.nditer(i[:,::2]): #prints elements one by one
    print(x)
#for x in i:
#    print(x)

[11 12 13 14]
[15 16 17 18]


# Enumeration(mentioning something in sequence)

In [11]:
import numpy as np
n = np.array([21,22,23])
for idx,x in np.ndenumerate(n): # prints values with index
    print(idx,x)

(0,) 21
(1,) 22
(2,) 23


# Concatenate

In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


# Stack

In [28]:
import numpy as np
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

stack = np.stack((arr1, arr2), axis=1) # axis1 means rowwise
print("Stack:",stack)

hstack = np.hstack((a1,a2))
print("Horizontal Stack:",hstack) #stack along rows

vstack = np.vstack((a1,a2))
print("Vertical Stack:",vstack) #stack along columns

dstack = np.dstack((a1,a2))
print("Depth Stack:",dstack) #stack along height

Stack: [[1 4]
 [2 5]
 [3 6]]
Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack: [[1 2 3]
 [4 5 6]]
Depth Stack: [[[1 4]
  [2 5]
  [3 6]]]


# Split

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3) # 3 is no of splits

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

# where method

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

# Search Sorted

In [30]:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right') #side='right' to return the right most index instead.
print(x)

2


# Sorting

In [ ]:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

# Filter

In [32]:
import numpy as np

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]

print(newarr)

[41 43]


# Import CSV in NumPy

In [116]:
import csv
data = []
with open('demo.csv','r') as csvfile:
    file_reader = csv.reader(csvfile,delimiter=',')
    for row in file_reader:
        data.append(row)
data = np.array(data)
print(data)

[['A' 'B' 'C' 'D']
 ['4' '8' '11' '45']
 ['5' '9' '12' '46']
 ['6' '10' '13' '47']
 ['7' '11' '14' '48']
 ['8' '12' '15' '49']
 ['9' '13' '16' '50']]


In [118]:
import pandas as pd
df = pd.read_csv('demo.csv')
print(df)

   A   B   C   D
0  4   8  11  45
1  5   9  12  46
2  6  10  13  47
3  7  11  14  48
4  8  12  15  49
5  9  13  16  50
